Repository UniKonf/vibey, pull requests merged in 2022-12, with the labels that each got.

#29 Add workflows
  .github/ISSUE_TEMPLATE/add-event.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/deploy.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/lint.yml
Labels: ci/cd

#34 fix CoC link
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: bug

#37 Fix: Workflows, eslint rules, build
  .eslintrc.json
  .gitignore
  .prettierignore
  .storybook/main.js
  .vscode/extensions.json
  .vscode/settings.json
  next.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#35 feat: integrate Gitpod and fix CI issues
  .gitpod.yml
  src/components/Event/Event.stories.tsx
Labels: enhancement
