Repository UniKonf/vibey, pull requests merged in 2023-06, with the labels that each got.

#234 💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS W/ A11Y PRINCIPLES
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: gssoc23, level2

#280 chore: Add Open Source Event
  public/images/events/open-source.jpg
  src/pages/events/index.tsx
Labels: gssoc23, level1

#282 Feat : Add workflow to assign PR to the author
  .github/workflows/author-assign-pr.yml
Labels: gssoc23, level2

#284 Added 'Builders Hub: BuidlWithUs' Event
  public/images/events/builders.webp
  src/components/Auth/Auth.tsx
  src/pages/events/index.tsx
Labels: good first issue, gssoc23, level1

#293 Change the color of the cards according to the theme
  src/components/upcoming/Event.tsx
  src/pages/hackathons/index.tsx
Labels: enhancement, gssoc23, level1

#243 Vishalk91 4 about issue
  public/images/events/Chandraprakash.png
  public/images/events/DeepandraKumar.png
  public/images/events/Kritika.png
  public/images/events/ManishTyagi.png
  public/static/Vibey-hero.png
  public/static/cfp.jpg
  public/static/event.jpg
  public/static/hackathon.jpg
  public/static/vibeydesign.png
  src/pages/about.tsx
Labels: gssoc23, level1

#354 Footer design fixed
  src/components/Logo.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
Labels: gssoc23, level2

#353 changes requested made
  src/components/layout/Footer.tsx
Labels: gssoc23, level1

#363 added overlay in events cards
  src/components/upcoming/Event.tsx
Labels: gssoc23, level1
