Repository UniKonf/vibey, pull requests merged in 2023-07, with the labels that each got.

#373 Feat: server validation
  server/package.json
  server/src/cpfs/cfp.router.js
  server/src/events/events.router.js
  server/src/hackathons/hackathon.router.js
  server/src/users/user.router.js
  server/src/validator-schema/validationSchema.js
Labels: gssoc23, level3

#403 Event details Page
  next.config.js
  src/components/DarkModebtn.tsx
  src/components/Event.tsx
  src/components/upcoming/Event.tsx
  src/lib/types.ts
  src/pages/about.tsx
  src/pages/events/[eventName].tsx
  src/pages/events/eventsData.tsx
  src/pages/events/index.tsx
Labels: gssoc23, level3

#413 feat: fetch cfp data for client side
  server/schema/cfps/CfpsSchema.js
  src/components/upcoming/CfpCardPage.tsx
  src/components/upcoming/Event.tsx
  src/lib/helper.ts
  src/lib/types.ts
  src/pages/cfps/index.tsx
  src/pages/events/index.tsx
  src/pages/hackathons/index.tsx
Labels: gssoc23, level3

#432 docs: run client server
  .env.example
  README.md
Labels: gssoc23, level3

#436 Create comment-on-pr.yml
  .github/workflows/comment-on-pr.yml
Labels: gssoc23, level2

#478 Update Footer.tsx
  src/components/layout/Footer.tsx
Labels: bug, typo

#482 feat: error handling
  README.md
  server/src/users/user.router.js
  src/components/Auth/Auth.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Register.tsx
  src/pages/dashboard/index.tsx
Labels: gssoc23, level3

#498 feat: add github action to lock new issues
  .github/workflows/issue-lock.yml
Labels: gssoc23, level2

#540 Fixed
  src/components/layout/Footer.tsx
Labels: gssoc23, level1

#546 feat: update cfp validation schema and mongo schema
  server/schema/cfps/CfpsSchema.js
  server/src/cpfs/cfp.router.js
  server/src/validator-schema/cfpValidation.js
Labels: gssoc23, level3
