Repository UniKonf/vibey, pull requests merged in 2023-08, with the labels that each got.

#549 added progress scrollbar
  git
  src/components/Hero.tsx
  src/components/Search/SearchBar.tsx
  src/components/layout/Header.tsx
  src/styles/globals.css
Labels: gssoc23, level3

#567 feat: add delete event feature
  server/schema/mongo.connect.js
  server/src/events/event.service.js
  src/components/Dashboard/DashboardEventCard.tsx
  src/components/Dashboard/Events.tsx
  src/pages/Contributors/GetContributor.tsx
  src/pages/api/events/delete-event.ts
Labels: new feature

#566 feat: add cfp dashboard
  src/components/Dashboard/Cfp/Cfps.tsx
  src/components/Dashboard/Cfp/DashboardCfpCard.tsx
  src/lib/types.ts
  src/pages/api/cfps/allcfps.ts
  src/pages/dashboard/index.tsx
Labels: gssoc23, level3, new feature

#534 Hackathons Page design
  pnpm-lock.yaml
  server/index.js
  server/pnpm-lock.yaml
  server/schema/hackathon/hackathonSchema.js
  server/schema/mongo.connect.js
  server/src/hackathons/hackathon.router.js
  server/src/validator-schema/validationSchema.js
  src/components/upcoming/HackathonCardPage.tsx
  src/lib/types.ts
  src/pages/hackathons/[slug].tsx
  src/pages/hackathons/index.tsx
Labels: gssoc23, level3

#574 fixing contrast issue in privacy policy page
  src/pages/privacy.tsx
Labels: bug, gssoc23, level1

#582 feat: add delete feature for hackathon
  src/components/Dashboard/Hackathons/DashboardHackathonCard.tsx
  src/components/Dashboard/Hackathons/Hackathons.tsx
  src/pages/api/hackathons/delete-hackathon.ts
Labels: gssoc23, level3, new feature

#573 Newsletter Functionality and Custom Email Template
  server/index.js
  server/package.json
  server/src/newsletter/newsletter.router.js
  server/src/newsletter/newsletter.service.js
  src/components/NewsLetter.tsx
Labels: gssoc23, level3

#606 feat: add edit feature in cfp
  server/src/cpfs/cfp.router.js
  server/src/cpfs/cfp.service.js
  src/components/NewsLetter.tsx
  src/pages/api/cfps/editCfp.ts
  src/pages/api/cfps/getCfp.ts
  src/pages/dashboard/cfp1/edit.tsx
  src/pages/dashboard/index.tsx
Labels: new feature

#604 feat: edit hackathon data
  server/schema/hackathon/hackathonSchema.js
  server/src/hackathons/hackathon.router.js
  src/components/NewsLetter.tsx
  src/lib/types.ts
  src/pages/api/hackathons/editHackathon.ts
  src/pages/api/hackathons/getHackathon.ts
  src/pages/dashboard/hackathon1/edit.tsx
Labels: new feature
